### PR TITLE
Cart Add, Get, Clear operations

### PR DESCRIPTION
**Pull request by mohammedwed**
Hi

I've added some of the missing operations, and I want to contribute to the project, here is a list of the operations:

-Cart Add
-Cart Get
-Cart Clear

### CODE REVIEW

**Comment by tinohager** [comment]
Thanks, i check the code in the next days...

**Comment by tinohager** [comment]
I have optimize and clean some parts of the code. I add a test logic in the website project.

Thanks for the commit, i push a new nuget package in the next days...

**Comment by mohammedwed** [comment]
Any time :)
Sounds great!

**Comment by mohammedwed** [comment]
Great!

**Pull request merged**
