### PR TITLE
Port to .Net Standard 2.0

### PR DESCRIPTION
**Pull request by ElanHasson**
For #31 

* Port to .Net Standard 2.0
* Updated dependencies on projects
* Switches Unit Tests to use embedded resources instead of File IO

### CODE REVIEW

**Comment by tinohager** [comment]
can you pull to the develop branch? i have created one

**Comment by ElanHasson** [comment]
The nuget package will automatically get created when a dotnet publish is done. You can then publish that package.

**Comment by tinohager** [comment]
Sorry but this pull requests have to many changes. And change the author of the library is for me not okay.

**Comment by tinohager** [comment]
Hi i have create a develop branch. You can check it, i have also update the Nager.ArticleNumber package. What is the reason for the unit test change to Resource?

**Comment by ElanHasson** [comment]
Hi Toni,

I've changed the author back to only you. 

I switched to resources because it's a bit cleaner for the output, and VS2017 not letting me set it to copy always in the new csproj.

I don't think I can edit the target branch of a PR, so i'll create a new PR.

**Comment by ElanHasson** [comment]
It also looks like you already made the changes-- no need for this PR.

**Comment by tinohager** [comment]
Hi Elan, i am happy for pull request but i like small changes and not one big one, you are welcome to send a pull request for resources in the unit test Project. 👍

**Pull request closed without merging**
