### PR TITLE
add variant support

### PR DESCRIPTION
**Pull request by lunchin**
This allows to get variant support when the item is the base product.

### CODE REVIEW

**Comment by tinohager** [comment]
Hi, have you a ASIN for me, i want test it?

**Comment by lunchin** [comment]
B0758FBH5T, B0742L3H1C, are a couple you find the product by getting the ParentASIN of item search.  By default it beings back the variants.

**Comment by lunchin** [comment]
Not sure why there is the conflict, I rebased my branch of master

**Comment by tinohager** [comment]
The conflict is no Problem.
I am try to get a example XML file, take you a item lookup with this asin B0758FBH5T? or item search? can you post a example Code please?

**Comment by lunchin** [comment]
`var response = _amazonClient.GetProducts(CatalogProducts
                    .Skip(index * 10)
                    .Take(take)
                    .Select(x => x.Item.ParentASIN ?? x.Item.ASIN)
                    .ToList());
if (response?.Items == null)
                {
                    continue;
                }

                catalog.AddRange(response.Items.Item.Select(GetAmazonProduct)
                    .Where(product => product != null));
[product.txt](https://github.com/tinohager/Nager.AmazonProductAdvertising/files/1278274/product.txt)

`

**Comment by tinohager** [comment]
Ok now i have the informations you make a ItemLookup with the following ResponseGroups BrowseNodes, Small, Variations i have optimize the TestUI and check your commit the next days thanks

**Comment by tinohager** [comment]
I have publish a new packages with your changes, thanks

**Pull request closed without merging**
