### PR TITLE
Add additional item search filters

### PR DESCRIPTION
**Pull request by jordanwallwork**
Additional search filters added for min/max price and condition. I also refactored the current stuff slightly to allow a method chaining syntax for configuring filters - usage is totally optional, it just happens to be something that I prefer

### CODE REVIEW

**Comment by tinohager** [comment]
Hi, i dont like the filter syntax i think for the most users it is to complex.
If you send a pull request with the ItemCondition i add this to the project.

I also like the AmazonItemSearchOperation changes.

**Comment by jordanwallwork** [comment]
Ok, I think the new filter syntax is pretty simple and expressive, but I'm not fussed about scrapping it if you're not a fan. I do think _something_ is needed though for specifying search filters though, as currently the only way to use the additional filters (even those that were there before like Sort) is something like

    var operation = wrapper.ItemSearchOperation(search, searchIndex, responseGroup);
    operation.Sort(AmazonSearchSort.Price, AmazonSearchSortOrder.Descending); // and whatever else
    var webResponse = wrapper.Request(operation);
    ItemSearchResponse response = null;
    if (webResponse.StatusCode == HttpStatusCode.OK)
    {
        response = XmlHelper.ParseXml<ItemSearchResponse>(webResponse.Content);
    }

Which to me is at the other end of the usability spectrum!

How would you feel about using a settings model? Something like

    var searchModel = new AmazonItemSearchModel {
        Available: true,
        Condition: ItemCondition.Refurbished,
        MinPrice: 1000,
        MaxPrice: 2500,
        Sort: AmazonSearchSort.Price,
        SortOrder: AmazonSearchSortOrder.Descending        
    };
    var result = wrapper.Search("canon eos", AmazonSearchIndex.Electronics, AmazonResponseGroup.Large, searchModel);

**Comment by jordanwallwork** [comment]
In fact don't w9rry

**Comment by jordanwallwork** [comment]
In

**Comment by jordanwallwork** [comment]
Sorry im on mobile and my phone started glitching then and pressing buttons on its own! I was trying to say don't worry, ill delete all of the filter syntax stuff and i can just use an extension method in my own project to get the filter config that i like

**Comment by tinohager** [comment]
Thanks

**Pull request merged**
